# Generated by Django 3.2.5 on 2021-07-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210725_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='business',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='dude',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_like'),
        ),
    ]
