# Generated by Django 3.2.5 on 2021-07-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_options'),
        ('network', '0007_auto_20210726_1259'),
    ]

    operations = [
    ]
